# MatrixCalc_CLI.py
# MatrixCalc_CLI.py is part of my Matrix Calculator Program Development.
# Currently i have developed matrix calculator in 4 different platoforms
# 1.Android   2.Linux(ShellScript)   3.Windows(Pythn & Tkinter)   4.Web(JavaScript)   
# (C) Daxeel Soni (github.com/daxeel)

print('Welcome to Matrix Calculator')
print('')
print('1. 2 cross 2 matrix type')
print('2. 3 cross 3 matrix type')
print('')
x=int(input('Enput your choice [1/2] : '))
if x == 1:
    print('a     b')
    print('c     d')
    print('')
    a=int(input('Enter value of a : '))
    b=int(input('Enter value of b : '))
    c=int(input('Enter value of c : '))
    d=int(input('Enter value of d : '))
    print('')
    print('Your matrix : ')
    print(a,'     ',b)
    print(c,'     ',d)
    print('')
    print('1. Calculate determinand')
    print('2. Calculate transpose')
    print('3. Calculate adjoint')
    print('4. Calculate inverse')
    print('')
    opt=int(input('What do want to do ? :'))
    if opt == 1:
        det=(d*a)-(c*b)
        print('Determinant is : ',det)
    elif opt == 2:
        print('Transpose is : ')
        print(a,'     ',c)
        print(b,'     ',d)
    elif opt == 3:
        print('Adjoint is : ')
        print(d,'     ',-b)
        print(-c,'     ',a)
    elif opt == 4:
        det=(d*a)-(c*b)
        print('Inverse is : ')
        print(d/det,'     ',-b/det)
        print(-c/det,'     ',a/det)
    else:
        print('Invalid operation!')
elif x == 2:
    print('a     b     c')
    print('d     e     f')
    print('g     h     i')
    print('')
    a=int(input('Enter value of a : '))
    b=int(input('Enter value of b : '))
    c=int(input('Enter value of c : '))
    d=int(input('Enter value of d : '))
    e=int(input('Enter value of e : '))
    f=int(input('Enter value of f : '))
    g=int(input('Enter value of g : '))
    h=int(input('Enter value of h : '))
    i=int(input('Enter value of i : '))
    print('')
    print('Your matrix : ')
    print(a,'     ',b,'     ',c)
    print(d,'     ',e,'     ',f)
    print(g,'     ',h,'     ',i)
    print('')
    print('1. Calculate determinand')
    print('2. Calculate transpose')
    print('3. Calculate adjoint')
    print('4. Calculate inverse')
    print('')
    opt=int(input('What do want to do ? :'))
    if opt == 1:
        det=(a*((e*i)-(h*f)))-(b*((d*i)-(g*f)))+(c*((d*h)-(e*g)))
        print('Determinant is : ',det)
    elif opt == 2:
        print('Transpose is : ')
        print(a,'     ',d,'     ',g)
        print(b,'     ',e,'     ',h)
        print(c,'     ',f,'     ',i)
    elif opt == 3:
        aa = (e*i)-(h*f)
        bb = (g*f)-(d*i)
        cc = (d*h)-(e*g)
        dd = (c*h)-(b*i)
        ee = (a*i)-(c*g)
        ff = (b*g)-(a*h)
        gg = (f*b)-(e*c)
        hh = (c*d)-(a*f)
        ii = (a*e)-(b*d)
        print('Adjoint is : ')
        print(aa,'     ',dd,'     ',gg)
        print(bb,'     ',ee,'     ',hh)
        print(cc,'     ',ff,'     ',ii)
    elif opt == 4:
        det=(a*((e*i)-(h*f)))-(b*((d*i)-(g*f)))+(c*((d*h)-(e*g)))
        aa = (e*i)-(h*f)
        bb = (g*f)-(d*i)
        cc = (d*h)-(e*g)
        dd = (c*h)-(b*i)
        ee = (a*i)-(c*g)
        ff = (b*g)-(a*h)
        gg = (f*b)-(e*c)
        hh = (c*d)-(a*f)
        ii = (a*e)-(b*d)
        print('Inverse is : ')
        print(format(aa/det, '.2f'),'     ',format(dd/det, '.2f'),'     ',format(gg/det, '.2f'))
        print(format(bb/det, '.2f'),'     ',format(ee/det, '.2f'),'     ',format(hh/det, '.2f'))
        print(format(cc/det, '.2f'),'     ',format(ff/det, '.2f'),'     ',format(ii/det, '.2f'))
    else:
        print('Invalid operation!')
else:
    print('Invalid input!')
